### ISSUE TITLE
関係ないけど

### ISSUE THREAD

**Issue by tsukumijima** [DoraemonAikouka/update-checker#1]
いつの間にか Twitter のアカウント消えてたけど、何かあったの…？

**Comment by DoraemonAikouka** [comment]
凍結

**Comment by tsukumijima** [comment]
あっちも凍結しちゃったんか
次のアカウントとかないの？

**Comment by DoraemonAikouka** [comment]
あるわけねえ

**Comment by tsukumijima** [comment]
もしかして：新しいアカウントが作れない

**Comment by DoraemonAikouka** [comment]
それに当たるっちゃ当たる

**Comment by DoraemonAikouka** [comment]
まあTwitterもやるだけ負担だしもうやりたくないってのが大きいかも

**Comment by tsukumijima** [comment]
そうなんだ………
Discordとかやってたっけ

**Comment by DoraemonAikouka** [comment]
やってる

**Comment by tsukumijima** [comment]
ID教えて🙏🙏

**Comment by DoraemonAikouka** [comment]
どっかプライベートにメッセージ取れるとこないかな
ここじゃ言いづらい
![image-removebg-preview (5)](https://user-images.githubusercontent.com/53083181/99079295-17bdbc80-2603-11eb-8ddf-30ad6fa4747d.png)

**Comment by tsukumijima** [comment]
じゃあこっちから教えるわ（追加されたら消す）
Torishima#8892

**Comment by DoraemonAikouka** [comment]
あい
